import { Inter, Vazirmatn } from "next/font/google";
import "./globals.css";
import Header from "@/Components/header";
import Footer from "@/Components/footer";
import MobileMenu from "@/Components/header/MobileMenu";

const inter = Inter({ subsets: ["latin"] });
const vazir = Vazirmatn({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa">
      <body className={`${inter.className} ${vazir.className} antialiased`}>
        <Header />
        <MobileMenu />
        <div className="md:max-w-7xl mx-auto font-[Vazirmatn]">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
